'use client'

import { useState } from 'react'
import { archiveProduct, createProduct, updateFulfillment, updateProductStock } from '@/app/actions/mlm'

type Product = { id: string; name: string; category: string; price: string; bp: number; stockQuantity: number }
type Order = { id: string; status: string; fulfillmentCity: string; total: string }

export default function AdminConsole({ products, orders }: { products: Product[]; orders: Order[] }) {
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  async function run(task: () => Promise<void>, success: string) { setBusy(true); try { await task(); setNotice(success) } catch { setNotice('Action failed. Check admin permissions and input.') } finally { setBusy(false) } }
  return <div className="mt-7 grid gap-6 lg:grid-cols-2">
    <section className="rounded-2xl border border-[#eadfdc] bg-white p-5 shadow-[0_8px_30px_rgba(73,37,32,0.04)]"><h2 className="font-semibold">Product operations</h2><div className="mt-4 grid gap-3"><button disabled={busy} onClick={() => { const name = window.prompt('Product name'); const category = window.prompt('Category'); const price = Number(window.prompt('Price PKR') ?? 0); const bp = Number(window.prompt('BP') ?? 0); const stockQuantity = Number(window.prompt('Stock quantity') ?? 0); if (!name || !category) return; void run(() => createProduct({ name, category, price, bp, stockQuantity, imageTone: '#ead0d0' }).then(() => undefined), 'Product created.') }} className="rounded-xl bg-[#762f42] px-3 py-2 text-sm font-semibold text-white">Add product</button>{products.map((product) => <div key={product.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-[#fbf6f4] p-3 text-sm"><span><b>{product.name}</b><br /><small>{product.category} · {product.stockQuantity} stock</small></span><span className="flex gap-2"><button disabled={busy} onClick={() => { const quantity = Number(window.prompt('New stock quantity', String(product.stockQuantity))); if (Number.isNaN(quantity)) return; void run(() => updateProductStock(product.id, quantity), 'Stock updated.') }} className="rounded-lg border border-[#eadfdc] px-2 py-1 text-xs">Stock</button><button disabled={busy} onClick={() => { if (window.confirm(`Archive ${product.name}?`)) void run(() => archiveProduct(product.id), 'Product archived.') }} className="rounded-lg border border-[#eadfdc] px-2 py-1 text-xs text-[#762f42]">Archive</button></span></div>)}</div></section>
    <section className="rounded-2xl border border-[#eadfdc] bg-white p-5 shadow-[0_8px_30px_rgba(73,37,32,0.04)]"><h2 className="font-semibold">Fulfillment operations</h2><div className="mt-4 grid gap-3">{orders.map((order) => <div key={order.id} className="rounded-xl bg-[#fbf6f4] p-3 text-sm"><div className="flex justify-between"><b>{order.id.slice(0, 8).toUpperCase()}</b><span>{order.status}</span></div><p className="mt-1 text-xs text-[#806f6a]">PKR {Number(order.total).toLocaleString()} · {order.fulfillmentCity}</p><button disabled={busy} onClick={() => { const status = window.prompt('Status: Packed, Shipped, Delivered or Cancelled', order.status); if (!status) return; const tracking = window.prompt('Tracking reference (optional)') ?? ''; void run(() => updateFulfillment(order.id, status, tracking), 'Fulfillment updated.') }} className="mt-2 rounded-lg border border-[#eadfdc] px-2 py-1 text-xs">Update status</button></div>)}</div></section>{notice && <p role="status" className="lg:col-span-2 rounded-xl bg-[#e8f2ed] p-3 text-sm text-[#3f8062]">{notice}</p>}</div>
}
