'use client'

import { useState } from 'react'
import { signOut } from '@/lib/auth-client'
import { cancelOrder, createOrder, requestWithdrawal } from '@/app/actions/mlm'
import { Award, BarChart3, Bell, Building2, ChevronDown, Copy, Gift, Home, Menu, Network, Package, Search, Settings2, ShoppingBag, Sparkles, Store, Users, Wallet, X } from 'lucide-react'

type Tab = 'Overview' | 'Network' | 'Shop' | 'Orders' | 'Wallet' | 'Rewards' | 'Fulfillment' | 'B2B' | 'Reports' | 'Admin'
type Product = { id: string; name: string; category: string; price: string; bp: number; imageTone: string }
type NetworkMember = { id: string; userId: string; rank: string; personalBp: number; personalSp: string; createdAt: Date }
type DashboardData = { products: Product[]; orders: Array<{ id: string; status: string; total: string; totalBp: number }>; rewards: Array<{ id: string; type: string; amount: string; bp: number; description: string; createdAt: Date }>; network: NetworkMember[]; profile: { rank: string; personalBp: number; personalSp: string; teamBp: number; walletBalance: string; referralCode: string } | null }
const nav: Array<{ label: Tab; icon: typeof Home }> = [{ label: 'Overview', icon: Home }, { label: 'Network', icon: Network }, { label: 'Shop', icon: ShoppingBag }, { label: 'Orders', icon: Package }, { label: 'Wallet', icon: Wallet }, { label: 'Rewards', icon: Gift }, { label: 'Fulfillment', icon: Store }, { label: 'B2B', icon: Building2 }, { label: 'Reports', icon: BarChart3 }, { label: 'Admin', icon: Settings2 }]
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl border border-[#eadfdc] bg-white p-5 shadow-[0_8px_30px_rgba(73,37,32,0.04)] ${className}`}>{children}</div> }
function Stat({ icon: Icon, label, value, note }: { icon: typeof Award; label: string; value: string; note: string }) { return <Card><div className="flex items-start justify-between"><div className="flex size-10 items-center justify-center rounded-xl bg-[#f6e9e9] text-[#762f42]"><Icon size={18} /></div><span className="text-xs font-semibold text-emerald-700">{note}</span></div><p className="mt-5 text-sm text-[#806f6a]">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></Card> }
function Heading({ title, description }: { title: string; description: string }) { return <><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#a78c83]">Oriflow workspace</p><h1 className="mt-2 font-serif text-3xl">{title}</h1><p className="mt-2 text-sm text-[#806f6a]">{description}</p></> }

export default function DistributorDashboard({ user, data }: { user: { name: string; email: string }; data: DashboardData }) {
  const [active, setActive] = useState<Tab>('Overview'); const [mobileOpen, setMobileOpen] = useState(false); const [cart, setCart] = useState<string[]>([]); const [notice, setNotice] = useState(''); const [submitting, setSubmitting] = useState(false); const [productSearch, setProductSearch] = useState(''); const [productCategory, setProductCategory] = useState('All'); const profile = data.profile
  const referral = `${typeof window !== 'undefined' ? window.location.origin : 'https://oriflow.in'}/join/${profile?.referralCode ?? 'ZIYA24'}`
  const categories = ['All', ...Array.from(new Set(data.products.map((product) => product.category)))]
  const filteredProducts = data.products.filter((product) => product.name.toLowerCase().includes(productSearch.toLowerCase()) && (productCategory === 'All' || product.category === productCategory))
  const cartItems = data.products.filter((p) => cart.includes(p.name))
  const cartTotal = cartItems.reduce((sum, item) => sum + Number(item.price), 0)
  async function submitOrder() {
    const items = data.products.filter((p) => cart.includes(p.name)).map((p) => ({ id: p.id, name: p.name, price: Number(p.price), bp: p.bp, quantity: 1 }))
    if (!items.length || submitting) return
    setSubmitting(true)
    setNotice('')
    try {
      await createOrder(items)
      setCart([])
      setNotice('Order submitted for fulfillment review.')
    } catch {
      setNotice('We could not submit this order. Please review your basket and try again.')
    } finally {
      setSubmitting(false)
    }
  }
  async function copyReferral() {
    await navigator.clipboard.writeText(referral)
    setNotice('Referral link copied to clipboard.')
  }
  return <div className="min-h-screen bg-[#fbf8f6] text-[#3b2522]"><aside className={`fixed inset-y-0 left-0 z-30 w-[260px] border-r border-[#eadfdc] bg-[#fffdfc] px-5 py-6 transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between px-2"><div className="flex items-center gap-2.5"><div className="flex size-9 items-center justify-center rounded-full bg-[#762f42] text-white"><Sparkles size={18} /></div><div><p className="font-serif text-xl text-[#762f42]">oriflow</p><p className="text-[9px] uppercase tracking-[0.22em] text-[#a78c83]">business portal</p></div></div><button className="lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X size={18} /></button></div><p className="mt-10 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#b19c95]">Workspace</p><nav className="mt-3 flex flex-col gap-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${active === label ? 'bg-[#f6e9e9] font-semibold text-[#762f42]' : 'text-[#806f6a] hover:bg-[#fbf3f1]'}`}><Icon size={18} />{label}</button>)}</nav><div className="absolute bottom-6 left-5 right-5 rounded-2xl bg-[#762f42] p-4 text-white"><p className="text-xs text-[#f2dfe2]">Current rank</p><p className="mt-1 font-semibold">{profile?.rank ?? 'Beauty Partner'}</p><div className="mt-3 h-1.5 rounded-full bg-white/20"><div className="h-full w-1/3 rounded-full bg-[#eac18b]" /></div><p className="mt-2 text-[11px] text-[#f2dfe2]">Qualification progress from live BP</p></div></aside><div className="lg:pl-[260px]"><header className="sticky top-0 z-20 flex h-[74px] items-center justify-between border-b border-[#eadfdc] bg-[#fffdfc]/95 px-5 backdrop-blur lg:px-9"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu size={21} /></button><div className="hidden items-center gap-2 rounded-xl border border-[#eadfdc] bg-white px-3 py-2 text-sm text-[#a18d87] md:flex"><Search size={16} /><input placeholder="Search team, orders..." className="w-48 bg-transparent outline-none" /></div><span className="font-serif text-lg text-[#762f42] md:hidden">oriflow</span></div><div className="flex items-center gap-4"><Bell size={19} className="text-[#806f6a]" /><button onClick={() => signOut({ fetchOptions: { onSuccess: () => window.location.assign('/sign-in') } })} className="flex items-center gap-2"><div className="flex size-9 items-center justify-center rounded-full bg-[#dec1b5] text-xs font-bold text-[#762f42]">{user.name.slice(0, 2).toUpperCase()}</div><span className="hidden text-sm font-semibold sm:block">{user.name}</span><ChevronDown size={15} /></button></div></header><main className="mx-auto max-w-[1400px] px-5 py-7 lg:px-9 lg:py-9">
  {active === 'Overview' && <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-[#98827b]">{new Intl.DateTimeFormat('en-PK', { dateStyle: 'full' }).format(new Date())}</p><h1 className="mt-1 font-serif text-3xl">Good morning, {user.name.split(' ')[0]}</h1><p className="mt-2 text-sm text-[#806f6a]">Your business, referral, BP and fulfillment overview.</p></div><button onClick={() => setActive('Shop')} className="rounded-xl bg-[#762f42] px-4 py-2.5 text-sm font-semibold text-white">Shop new arrivals</button></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Award} label="Personal BP" value={`${profile?.personalBp ?? 0} BP`} note="Live ledger" /><Stat icon={Network} label="Team BP" value={`${profile?.teamBp ?? 0} BP`} note="Live network" /><Stat icon={Wallet} label="Available wallet" value={`PKR ${Number(profile?.walletBalance ?? 0).toLocaleString()}`} note="Withdrawable" /><Stat icon={Users} label="Direct team" value={`${data.network.length} members`} note="Live network" /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold">Sales & BP performance</h2><div className="mt-7 flex h-44 items-end gap-4">{['Apr','May','Jun','Jul','Aug','Sep'].map((m, i) => <div key={m} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="flex h-full items-end gap-1"><div className="w-3 rounded-t bg-[#ead0d0]" style={{ height: `${40 + i * 7}%` }} /><div className="w-3 rounded-t bg-[#762f42]" style={{ height: `${52 + i * 6}%` }} /></div><span className="text-[10px] text-[#a78c83]">{m}</span></div>)}</div></Card><Card><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#a78c83]">Referral engine</p><h2 className="mt-2 font-serif text-2xl">Grow your circle</h2><p className="mt-2 text-sm text-[#806f6a]">Invite customers and consultants with your permanent referral link.</p></div><Gift className="text-[#b57c3c]" /></div><div className="mt-5 flex items-center gap-2 rounded-xl bg-[#fbf3f1] p-3"><code className="min-w-0 flex-1 truncate text-xs text-[#762f42]">{referral}</code><button onClick={() => navigator.clipboard?.writeText(referral)} aria-label="Copy referral link"><Copy size={15} /></button></div><p className="mt-3 text-xs text-[#3f8062]">12 direct referrals · PKR 6,250 earned</p></Card></div></>}
  {active === 'Network' && <><Heading title="Network & genealogy" description="Track direct referrals, team members, customers, BP contribution and performance." /><Card className="mt-7 overflow-hidden p-0"><div className="grid grid-cols-4 bg-[#fbf6f4] px-4 py-3 text-[11px] font-semibold uppercase text-[#a78c83]"><span>Member</span><span>Rank</span><span>BP / SP</span><span>Status</span></div>{data.network.length ? data.network.map((member) => <div key={member.id} className="grid grid-cols-4 items-center border-t border-[#f0e7e4] px-4 py-4 text-sm"><b>{member.userId.slice(0, 12)}…</b><span className="text-[#806f6a]">{member.rank}</span><span>{member.personalBp.toLocaleString()} BP<br /><small className="text-[#98827b]">{Number(member.personalSp).toLocaleString()} SP</small></span><span className="text-emerald-700">Active</span></div>) : <div className="p-8 text-center text-sm text-[#806f6a]">No direct referrals yet. Share your referral link to grow your network.</div>}</Card></>}
  {active === 'Shop' && <><Heading title="Product centre" description="Retail and partner pricing with BP/SP earning and campaign-ready catalog." />{cartItems.length > 0 && <Card className="mt-6 flex flex-col justify-between gap-4 border-[#762f42]/20 bg-[#fff8f7] sm:flex-row sm:items-center"><div><p className="text-sm font-semibold">Basket ready for fulfillment</p><p className="mt-1 text-xs text-[#806f6a]">{cartItems.length} product{cartItems.length === 1 ? '' : 's'} · PKR {cartTotal.toLocaleString()} · {cartItems.reduce((sum, item) => sum + item.bp, 0)} BP</p></div><button onClick={() => setActive('Orders')} className="rounded-xl bg-[#762f42] px-4 py-2.5 text-sm font-semibold text-white">Review basket</button></Card>}<div className="mt-7 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#a78c83]" size={17} /><input aria-label="Search products" value={productSearch} onChange={(event) => setProductSearch(event.target.value)} placeholder="Search products, skincare, fragrance..." className="w-full rounded-xl border border-[#eadfdc] bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-[#762f42]" /></label><select aria-label="Filter by category" value={productCategory} onChange={(event) => setProductCategory(event.target.value)} className="rounded-xl border border-[#eadfdc] bg-white px-4 py-3 text-sm outline-none focus:border-[#762f42]">{categories.map((category) => <option key={category}>{category}</option>)}</select></div><div className="mt-5 flex items-center justify-between"><p className="text-xs text-[#806f6a]">Showing {filteredProducts.length} of {data.products.length} products</p><span className="rounded-full bg-[#f6e9e9] px-3 py-1 text-xs font-semibold text-[#762f42]">PKR pricing</span></div><div className="mt-4 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{filteredProducts.map((p) => <Card key={p.id} className="overflow-hidden p-0"><div className={`h-36 bg-gradient-to-br ${p.imageTone} p-4`}><span className="rounded-full bg-white/70 px-2 py-1 text-[10px] font-semibold text-[#762f42]">{p.category}</span></div><div className="p-4"><h3 className="font-semibold">{p.name}</h3><div className="mt-2 flex justify-between text-sm"><b>PKR {Number(p.price).toLocaleString()}</b><span className="text-[#a36e32]">{p.bp} BP · {p.bp * 2} SP</span></div><button onClick={() => setCart((c) => c.includes(p.name) ? c : [...c, p.name])} className="mt-4 w-full rounded-xl bg-[#762f42] px-3 py-2.5 text-sm font-semibold text-white">{cart.includes(p.name) ? 'Added to basket' : 'Add to basket'}</button></div></Card>)}</div></>}
  {active === 'Orders' && <><Heading title="Orders & fulfillment" description="Track customer, consultant and B2B orders through local city fulfillment points." />{notice && <p role="status" className="mt-5 rounded-xl bg-[#e8f2ed] p-4 text-sm text-[#3f8062]">{notice}</p>}{cartItems.length > 0 && <Card className="mt-7 border-[#762f42]/20 bg-[#fff8f7]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Basket review</h2><p className="mt-1 text-sm text-[#806f6a]">Confirm your PKR order before sending it to fulfillment.</p></div><b className="text-[#762f42]">PKR {cartTotal.toLocaleString()}</b></div><div className="mt-4 flex flex-col gap-3">{cartItems.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-white px-4 py-3 text-sm"><span><b>{item.name}</b><span className="ml-2 text-xs text-[#98827b]">{item.bp} BP · {item.bp * 2} SP</span></span><button aria-label={`Remove ${item.name} from basket`} onClick={() => setCart((current) => current.filter((name) => name !== item.name))} className="text-xs font-semibold text-[#762f42]">Remove</button></div>)}</div><button disabled={submitting} onClick={submitOrder} className="mt-5 rounded-xl bg-[#762f42] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60">{submitting ? 'Submitting order…' : 'Submit basket for fulfillment'}</button></Card>}<Card className="mt-7"><h2 className="font-semibold">Order lifecycle</h2>{data.orders.map((o) => <div key={o.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#f0e7e4] py-4 last:border-0"><div><b>{o.id}</b><p className="text-xs text-[#98827b]">{o.totalBp} BP · local routing</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-700">{o.status}</span><b>PKR {Number(o.total).toLocaleString()}</b>{o.status === 'Pending' && <button onClick={async () => { setSubmitting(true); try { await cancelOrder(o.id); setNotice('Order cancelled successfully.'); } catch { setNotice('Order could not be cancelled.'); } finally { setSubmitting(false) } }} className="text-xs font-semibold text-[#762f42]">Cancel</button>}</div></div>) }</Card></>}
  {active === 'Wallet' && <><Heading title="Wallet & earnings" description="Commission ledger, referral bonuses, rank rewards and withdrawals." /><div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={Wallet} label="Available payout" value={`PKR ${Number(profile?.walletBalance ?? 0).toLocaleString()}`} note="Ready to withdraw" /><Stat icon={Gift} label="Referral rewards" value={`PKR ${data.rewards.reduce((sum, reward) => sum + Number(reward.amount), 0).toLocaleString()}`} note={`${data.rewards.length} ledger entries`} /><Stat icon={Award} label="Current rank" value={profile?.rank ?? 'Beauty Partner'} note={`${profile?.personalBp ?? 0} BP`} /></div><Card className="mt-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">Request payout</h2><p className="mt-1 text-sm text-[#806f6a]">Minimum PKR 500. Requests are held for admin approval.</p></div><button disabled={submitting} onClick={async () => { const amount = Number(window.prompt('Enter withdrawal amount in PKR') ?? 0); if (!amount) return; setSubmitting(true); try { await requestWithdrawal(amount); setNotice('Withdrawal request submitted for admin approval.'); } catch { setNotice('Withdrawal could not be submitted. Check your available balance.'); } finally { setSubmitting(false) } }} className="rounded-xl bg-[#762f42] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{submitting ? 'Submitting…' : 'Request withdrawal'}</button></div>{notice && <p role="status" className="mt-4 rounded-xl bg-[#e8f2ed] p-3 text-sm text-[#3f8062]">{notice}</p>}</Card><Card className="mt-6"><h2 className="font-semibold">Immutable ledger</h2>{data.rewards.length ? data.rewards.map((reward) => <div key={reward.id} className="flex justify-between border-b border-[#f0e7e4] py-4 text-sm last:border-0"><span><b>{reward.type}</b><br /><small className="text-[#98827b]">{reward.description}</small></span><b className={Number(reward.amount) >= 0 ? 'text-emerald-700' : 'text-[#762f42]'}>{Number(reward.amount) >= 0 ? '+' : ''}PKR {Number(reward.amount).toLocaleString()}</b></div>) : <p className="py-5 text-sm text-[#806f6a]">Your rewards ledger will appear here after your first qualifying activity.</p>}</Card></>}
  {active === 'B2B' && <><Heading title="B2B wholesale centre" description="Business approval, tier pricing, MOQ, invoices and bulk orders." /><div className="mt-7 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold">Business profile</h2><div className="mt-5 grid gap-4 text-sm"><div className="flex justify-between"><span>Account status</span><b className="text-amber-700">Review required</b></div><div className="flex justify-between"><span>Wholesale tier</span><b>Standard · rules pending</b></div><div className="flex justify-between"><span>Assigned city</span><b>Not assigned</b></div><div className="flex justify-between"><span>Minimum order</span><b>Configured by admin</b></div></div></Card><Card><h2 className="font-semibold">Wholesale actions</h2><div className="mt-5 grid gap-3"><button onClick={() => { setActive('Shop'); setNotice('Wholesale catalog opened. Partner pricing is applied at checkout.') }} className="rounded-xl bg-[#762f42] p-3 text-left text-sm font-semibold text-white">Browse wholesale catalog →</button><button onClick={() => setNotice('Invoice center is ready. Invoices will appear after an order is fulfilled.')} className="rounded-xl border border-[#eadfdc] p-3 text-left text-sm font-semibold">Download invoices →</button></div></Card></div></>}
  {active === 'Rewards' && <><Heading title="Rewards & rank progress" description="Transparent qualification rules, BP/SP milestones, bonuses and campaign incentives." /><div className="mt-7 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold">Rank ladder</h2>{[[profile?.rank ?? 'Beauty Partner', `${profile?.personalBp ?? 0} personal BP`, 'Current'],['Senior Consultant', `${profile?.teamBp ?? 0} team BP`, 'Qualification pending'],['Gold Director', 'Business rules not configured', 'Unavailable']].map(([rank, progress, state]) => <div key={rank} className="mt-4 rounded-xl border border-[#f0e7e4] p-4"><div className="flex justify-between text-sm"><b>{rank}</b><span className="text-[#806f6a]">{state}</span></div><p className="mt-2 text-xs text-[#98827b]">{progress}</p><div className="mt-3 h-1.5 rounded-full bg-[#f4e9e6]"><div className="h-full w-1/3 rounded-full bg-[#762f42]" /></div></div>)}</Card><Card><h2 className="font-semibold">Campaign rewards</h2>{['Campaign rules pending admin setup','Rank qualification uses live BP/SP','Reward campaigns will appear here'].map((x) => <div key={x} className="mt-3 flex items-center justify-between rounded-xl bg-[#fbf6f4] p-4 text-sm"><span>{x}</span><span className="font-semibold text-[#762f42]">Setup pending</span></div>)}</Card></div></>}
  {active === 'Fulfillment' && <><Heading title="City fulfillment" description="Route orders by city, service area, inventory availability and local sales point." /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{['Multan','Lahore','Karachi','Islamabad'].map((city) => <Card key={city}><div className="flex items-center justify-between"><b>{city}</b><span className="text-xs text-emerald-700">Service area</span></div><p className="mt-5 text-2xl font-semibold">{data.orders.length}</p><p className="mt-1 text-xs text-[#98827b]">Orders visible to your account · inventory sync pending</p><button onClick={() => setActive('Orders')} className="mt-4 w-full rounded-xl border border-[#eadfdc] px-3 py-2 text-xs font-semibold">View orders</button></Card>)}</div><Card className="mt-6"><h2 className="font-semibold">Routing priority</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Exact sales point','City inventory','Service area','Main warehouse fallback'].map((x, i) => <div key={x} className="rounded-xl bg-[#fbf6f4] p-4 text-sm"><span className="text-xs text-[#a78c83]">0{i + 1}</span><p className="mt-2 font-medium">{x}</p></div>)}</div></Card></>}
  {active === 'Reports' && <><Heading title="Reports & analytics" description="Monitor sales, BP/SP, commissions, inventory, B2B performance and withdrawals." /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={BarChart3} label="Gross sales" value={`PKR ${data.orders.reduce((sum, order) => sum + Number(order.total), 0).toLocaleString()}`} note={`${data.orders.length} orders`} /><Stat icon={Package} label="Orders" value={String(data.orders.length)} note="Live ledger" /><Stat icon={Award} label="Total BP" value={`${data.orders.reduce((sum, order) => sum + order.totalBp, 0).toLocaleString()} BP`} note="From orders" /><Stat icon={Wallet} label="Rewards credited" value={`PKR ${data.rewards.filter((reward) => Number(reward.amount) > 0).reduce((sum, reward) => sum + Number(reward.amount), 0).toLocaleString()}`} note="Live ledger" /></div><Card className="mt-6"><h2 className="font-semibold">Monthly sales trend</h2><div className="mt-7 flex h-44 items-end gap-3">{[48,56,44,66,72,82,91,76,88,94,100,96].map((height, i) => <div key={i} className="flex flex-1 flex-col items-center justify-end gap-2"><div className="w-full rounded-t bg-[#762f42]" style={{ height: `${height}%` }} /><span className="text-[10px] text-[#a78c83]">{i + 1}</span></div>)}</div></Card></>}
  {active === 'Admin' && <><Heading title="Administration & controls" description="Role-based operations for cities, franchises, inventory, commissions, campaigns and reports." /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={BarChart3} label="Recorded sales" value={`PKR ${data.orders.reduce((sum, order) => sum + Number(order.total), 0).toLocaleString()}`} note={`${data.orders.length} orders`} /><Stat icon={Store} label="Fulfillment cities" value="4" note="Configured" /><Stat icon={Users} label="Direct consultants" value={String(data.network.length)} note="Live network" /><Stat icon={Wallet} label="Commission credited" value={`PKR ${data.rewards.filter((reward) => Number(reward.amount) > 0).reduce((sum, reward) => sum + Number(reward.amount), 0).toLocaleString()}`} note="Ledger total" /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold">Configurable business rules</h2>{['MLM levels & rate snapshots','City Head commissions','Ranks & rewards','Shipping zones & routing'].map((x) => <button key={x} className="mt-3 flex w-full justify-between rounded-xl border border-[#f0e7e4] p-4 text-left text-sm font-medium">{x}<span className="text-[#762f42]">→</span></button>)}</Card><Card><h2 className="font-semibold">Operations queue</h2>{['12 withdrawal requests','4 B2B approvals','8 reviews to moderate','6 low-stock alerts'].map((x) => <div key={x} className="mt-3 rounded-xl bg-[#fbf6f4] p-4 text-sm">{x}</div>)}</Card></div></>}
 </main></div></div>
}

export { Stat as StatCard }
